mateo-mugnaini/FOODLAND

api/.gitignore
api/index.js
api/package-lock.json
api/package.json

update Create server

---

client/src/App.js
client/src/Components/Cards/Products.css
client/src/Components/Cards/Products.jsx
client/src/Components/products.js

Errors were corrected and each card was linked in detail. It remains to solve detail route that does not work

bug fixes and css in products.jsx component

---

api/index.js
api/src/routes/userRoutes.js

ruta "/api/users" para que devuelva los usuarios. Por el momento solo devuelve el usuario admin que tiene permiso de adminitrador y el usuario customer. Hoy no tiene middlewares pero va a haber q generar middleware para pedir autorizacion y si es admin

ruta para get de users

---

api/src/routes/products.js

ruta para el detalle de un producto /api/products/slug/:id

routing products details

---

api/index.js
client/src/App.js
client/src/Components/Cards/Products.jsx
client/src/redux/actions.js

Se corrigio el componente Products.jsx para  muestre los productos traidos de la base de datos. Si no hay productos muestra un mensaje de no hay productos

Array products

---

api/src/routes/userRoutes.js

Rutas del userRouter
Ruta para traer un usuario --> userRouter.get("/:id")
Ruta para que el usuario actualice sus datos --> userRouter.put("/profile")
Ruta para que el admin actualice un usuario --> userRouter.put("/:id")
Ruta para loguearse --> userRouter.post("/signin")
Ruta para crear usuario -->userRouter.post(	"/signup")
Ruta para que el admin borre usuario-->userRouter.delete("/:id")

rutas del user (ver explicacion)

---

client/src/Components/Footer/Footer.jsx
client/src/redux/action-types.js
client/src/redux/actions.js

Form function Footer to 2do string
Warning fix: Action.types

Footer- changes-config

---

client/src/Components/NavBar/SearchBar.jsx
client/src/redux/action-types.js
client/src/redux/actions.js
client/src/redux/reducer.js

I can't see the results. I update it to be able to bring the new repo

Changes action -redux

---

client/src/redux/actions.js

update Actions 

---

client/src/App.js
client/src/Components/Cards/categoryContainer.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/redux/actions.js

updated components

---

client/src/App.js
client/src/Components/Cards/categoryContainer.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Components/NavBar/SearchBar.jsx
client/src/Views/Home/Home.jsx
client/src/redux/action-types.js
client/src/redux/actions.js
client/src/redux/reducer.js

productos filtrados por categoria, modificada la action GET ALL PRODUCTS y archivo productsContainer, y categoryContainer

filtered products

---

client/src/Components/FormCreateProduct/FormCreateProduct.css
client/src/Components/FormCreateProduct/FormCreateProduct.jsx

Se mojoro el css en el formulario de crear productos

Form products

---

client/src/Components/Cards/cards.css
client/src/Components/Cards/productsContainer.jsx
client/src/redux/action-types.js
client/src/redux/actions.js
client/src/redux/reducer.js

filtros de ordenamiento para los productos , de la A-Z y viceversa, y de mayor a menor precio y visceversa.

order filters

---

api/src/assets/data.js
api/src/models/product.js
api/src/routes/products.js

ruta para traer las categorias y las fotos

ruta get categories con foto de categoria

---

client/package-lock.json
client/src/App.js
client/src/Components/Cards/Filters.css
client/src/Components/Cards/Filters.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Components/NavBar/SearchBar.jsx
client/src/redux/action-types.js
client/src/redux/actions.js
client/src/redux/reducer.js

el  problema es hacer llegar la Info al reducer para que cambie el state... o nose

Filter 1 - Me 0

---

client/src/App.js
client/src/Components/FormCreateProduct/FormCreateProduct.css
client/src/Components/FormCreateProduct/FormCreateProduct.jsx
client/src/Views/CreateProduct/CreateProduct.css
client/src/Views/CreateProduct/CreateProduct.jsx

Se creo una carpeta en views donde se importa el formulario y se configura la pagina

Correccion del Formulario de Crear Productos

---

client/src/Components/FormCreateProduct/FormCreateProduct.jsx
client/src/redux/action-types.js
client/src/redux/actions.js
client/src/redux/reducer.js

Ya esta habilitado la funcion de crear una nueva categoria

Update Form Create Product

---

client/src/Components/Cards/Filters.jsx

change the request for products and now it works

filter price ON

---

client/src/Components/NavBar/NavBar.css
client/src/Components/NavBar/NavBar.jsx
client/src/Components/NavBar/SearchBar.css

Se actualizaron los estilos del navbar.

Estilos en el navbar

---

client/src/Components/FormCreateProduct/FormCreateProduct.css
client/src/Components/FormCreateProduct/FormCreateProduct.jsx

Nuevos avances en los estilos del formulario.
Se agrego una vista previa del producto

Update2 estilos formulario crear product

---

client/src/Components/FormCreateProduct/FormCreateProduct.jsx

Se puso el select y se comento el input de agregar una nueva categoria

Form Create product update

---

client/src/Components/Cards/Filters.jsx
client/src/Components/Cards/cards.css
client/src/Components/Cards/categoryContainer.jsx
client/src/Components/Cards/productCard.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Components/Rating/rating.jsx
client/src/Views/Detail/DetailCard.css
client/src/Views/Detail/DetailCard.jsx
client/src/Views/Home/Home.jsx

arreglo css de todo el flujo de productos y breadcrumb

Css and breadcrumb

---

client/src/Components/FormCreateProduct/FormCreateProduct.css
client/src/Components/FormCreateProduct/FormCreateProduct.jsx
client/src/Components/FormCreateProduct/Validations.js

Arreglos en el formulario

---

api/src/assets/data.js

corrección en la base de datos

correcion database

---

client/src/App.js
client/src/Components/FormRegisterUser/FormRegister.jsx
client/src/Views/Register/Register.jsx

Se creo el formulario de registro y se modulo un poco su contenido.
Hay que ver bien que datos vamos a pedir

Creacion de formulario de registro

---

client/package-lock.json
client/package.json
client/src/Components/FormRegisterUser/FormRegister.css
client/src/Components/FormRegisterUser/FormRegister.jsx
client/src/Views/Register/Register.css
client/src/Views/Register/Register.jsx

El formulario envia los datos al back pero no estoy logrando que redireccione al home o al login  y tampoco logro que muestre el alert que le di. HAY QUE INSTALAR sweetalert2

Correcciones en el form de registro

---

client/src/Components/FormCreateProduct/FormCreateProduct.css
client/src/Components/FormCreateProduct/FormCreateProduct.jsx

Se modifico el css en el boton de return home en el formulario de crear productos

Arreglos en el css

---

client/src/Components/FormRegisterUser/FormRegister.jsx
client/src/Components/FormRegisterUser/ValidationsRegister.js

Se agregaron validaciones al formulario de registro

Form register

---

client/src/Components/FormRegisterUser/FormRegister.jsx
client/src/Components/Stock/Stock.jsx

Se cambio la redireccion a la hora de crear el usuario, una vez creada este se redirecciona al login no como antes que se redireccionaba al home

Correccion

---

client/src/Components/CartItem/CartItem.jsx
client/src/Components/Footer/Footer.css
client/src/Views/MyCart/MyCart.css
client/src/Views/MyCart/MyCart.jsx

Added delete button functionality

Update My cart

---

api/src/routes/order.js

Arreglé esos 2 imports que rompian el back

changes imports

---

client/src/redux/actions/userActions.js

se repara el error en el logeo

refactor loginOut

---

client/src/Views/UserProfile/UserProfile.jsx

Cambio para ver la info del usuario que esta logueado, se cambio el hardcodeo que habia

Cambios para ver info de user login

---

api/index.js

Agrega una variable en el process de nombre ORIGIN

arreglo cors

---

client/src/Views/UserProfile/UserProfile.jsx

Se le agrego la funcionalidad de logout al btn del perfil del usuario. 
Tambien se creo el componente para el formulario para editar la informacion

btn Logout profile

---

api/src/routes/order.js

agregue isadmin a una de las rutas
saqué una parte del código de la ruta get q estaba demas xq el paginado lo hacen en el front 
notas para q los del front sepan para q sirven

cambios menores en las rutas de ordenes

---

client/src/index.js

se hace una modificacion en el front y back para que tome variables de entorno para la parte del deploy que esta fallando la integracion con terceros
agregar en el front las siguientes variables de entorno 
REACT_APP_CLIENT_ID=eA4eUwWgtnmy6QQulVAYhP1WpJ9uD7u6
REACT_APP_DOMAIN=dev-7azhwajhv4hw38nz.us.auth0.com
estas son las llaves y dominios de la ruta de deploy para que funcione

refactor code auth0

---

client/src/Components/Cards/categoryContainer.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Texts/legalPopup.txt
client/src/Texts/returnPolicyPopup.txt
client/src/Views/Detail/DetailCard.jsx
client/src/Views/UserProfile/UserProfile.css
client/src/Views/UserProfile/UserProfile.jsx
client/src/redux/actions.js
client/src/redux/actions/productActions.js
client/src/redux/constants/productConstants.js
client/src/redux/reducer.js

User profile

---

api/index.js
client/src/App.js
client/src/Components/Stock/FormUpdateProduct.css
client/src/Components/Stock/FormUpdateProduct.jsx
client/src/Components/Stock/Stock.jsx
client/src/Views/UpdateProduct/UpdateProduct.jsx
client/src/redux/actions/productActions.js

Se corrigio el login error del 10/5

Correccion error login

---

client/src/Components/Cards/productsContainer.jsx

Se corrigio un error al traer los productos a las categorias. FALTA CORREGIR EL FILTRADO

Correccion traer productos

---

api/src/routes/products.js
client/src/Components/Stock/FormUpdateProduct.jsx
client/src/Components/Stock/Stock.jsx
client/src/Views/CreateProduct/CreateProduct.jsx
client/src/Views/Stock/StockViews.jsx
client/src/Views/UpdateProduct/UpdateProduct.jsx
client/src/redux/actions/productActions.js

Se creo el formulario para editar el producto, junto a un alert que notifica que el producto esta actualizado

Formulario de editar producto 

---

client/src/Components/Cards/productCard.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Views/Order/placeOrderScreen.jsx

se soluciona el error que hacia que cuando se agregaba de la pagina de categorias un producto solo agregaba el ultimo que se le daba click, ya ahora agrega todos los que se les de click

add to cart error fixed

---

api/index.js
api/package-lock.json
api/package.json
api/src/routes/userRoutes.js
client/src/Components/Cards/categoryContainer.jsx
client/src/Components/sentEmail.jsx

funcionalidad creada- falta aplicar a sitio correspondiente

nueva funcionalidad mail

---

client/src/App.js
client/src/Components/NavBar/NavBar.jsx
client/src/Views/Home/Home.css
client/src/Views/Home/Home.jsx
client/src/Views/UserProfile/UserProfile.jsx

Se modifico el navbar para que si el user es admin no vea el icono del carrito y el user no admin si lo vea.
Se diseño la sidebar para navegar en el administrador por todos los paneles.
Falta implementar el overview, los usuarios y algunas funcionalidades de editar productos.

Correcciones en el administrador

---

client/src/Components/EditProfile/EditProfile.jsx
client/src/Views/UserProfile/UserProfile.jsx

Se creo el componente para que el user modifique sus datos.

Edit Profile user

---

api/package-lock.json
client/package-lock.json
client/src/Components/Cards/productsContainer.jsx
client/src/Components/FormCreateProduct/FormCreateProduct.jsx
client/src/Views/UserProfile/UserProfile.jsx
client/src/redux/actions/productActions.js
client/src/redux/constants/productConstants.js
client/src/redux/reducers/productReducers.js

Se modifico el action para que cree el producto verificando el token si es administrador

Home admin

---

client/src/Components/Checkout/CheckOut.css
client/src/Components/Checkout/CheckOut.jsx
client/src/Components/ListUser-Admin/Users.css
client/src/Components/ListUser-Admin/Users.jsx
client/src/Components/PayPalButton/PaypalButton.jsx
client/src/Components/PayPalButton/paypal.css
client/src/Views/Order/placeOrderScreen.css
client/src/Views/Order/placeOrderScreen.jsx
client/src/redux/actions/userActions.js

la ruta no me deja modificar el active. Algun back que me ayude?

Sigue sin funcionarme pero le cambie el css (No rompe)

---

api/index.js
api/package-lock.json
api/package.json
api/src/routes/uploadRoute.js
client/src/Components/FormCreateProduct/FormCreateProduct.jsx

la imagen se carga bien en cloudinary
falta seguir el proceso de crear el producto incluyendo la imagen porque lo crea sin este campo

cloudinary

---

api/src/routes/userRoutes.js

ruta para q el admin borre un usuario en lugar de desactivarlo

ruta delete user del back

---

client/src/Components/Reviews/Reviews.jsx

para que redirija al login si el usuario no está logueado

redireccionamiento al login

---

client/src/Components/Stock/FormUpdateProduct.jsx

Se implemento cloudinary en el formulario de update products

Se adapto el update con cloudinary

---

client/src/Components/OdersAdmin/OrdersAdmin.css
client/src/Components/OdersAdmin/OrdersAdmin.jsx
client/src/Views/Home/Home.css
client/src/Views/Home/Home.jsx
client/src/redux/actions/orderActions.js
client/src/redux/reducers/orderReducers.js

Se creo el componente de las ordenes del administrador. Se ve todas las ventas con sus datos correspondientes

ordenes del administrador

---

client/src/Components/ListUser-Admin/Users.css
client/src/Components/ListUser-Admin/Users.jsx
client/src/redux/actions/userActions.js
client/src/redux/constants/userConstants.js
client/src/redux/reducers/userReducers.js

Update list user

---

client/src/redux/reducers/productReducers.js

I removed auxiliaries that we no longer need

remove aux - sort

---

client/src/redux/reducers/cartReducers.js

resuelvo un problema despues de comprar con paypal se rompia al pagina

fixed cart solve

---

api/src/routes/order.js

se configura todo lo de envio de email al pagar la order no al crearla

email sent upon payment of order

---

client/src/Components/Cards/productsContainer.jsx
client/src/Components/ListUser-Admin/Users.jsx
client/src/Components/Reviews/Reviews.css
client/src/Components/Reviews/Reviews.jsx
client/src/Components/Stock/FormUpdateProduct.jsx
client/src/Views/Detail/DetailCard.css
client/src/Views/Detail/DetailCard.jsx
client/src/Views/MyCart/MyCart.css
client/src/Views/Order/placeOrderScreen.jsx
client/src/redux/actions/orderActions.js

add AlertsI placed alerts, buttons, fixed sort in /ListUser + ...

Changes HTML y CSS

---

client/src/Components/Cards/productCard.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Views/Detail/DetailCard.jsx
client/src/redux/actions.js

Se agrega que verifique que halla stock y activo el producto

arrangement in the add to cart button

---

client/src/Views/Detail/DetailCard.jsx
client/src/Views/MyCart/MyCart.jsx

se arregla el renderizado del carrito en mycart y detail

Fixed cart

---

client/src/Components/UserOrders/UserOrders.jsx

El problema era que por fuera del map agarraba el id de la orden , ya con el map agarra bien la ruta , el unico problema es que en las primeras compras , como tenian otro ID , no se van a ver , las nuevas que realices ahora si!

fixing Link

---

client/src/Components/Cards/productsContainer.jsx

Correccion del paginado de los productos. Ahora muestra 10 paginas un btn para atras otro para ir a la primer pagina otro para next y para la ultima pagina, tambien se destaca la pagina en la cual te encontras

Correccion del paginado

---

client/src/Views/Order/placeOrderScreen.css
client/src/Views/Order/placeOrderScreen.jsx

Se le agrego un funcion al btn de placeorder que al no cumplir las condiciones este se muestre en rojo

updte del boton placeorder

---

client/src/App.js
client/src/Views/About/About.css
client/src/Views/About/About.jsx
client/src/Views/Login/login2.jsx
client/src/Views/Order/placeOrderScreen.jsx

Se modifico el css en el about
y agregamos un nuevo login para que te redireccione al placeorder

Actualizacion de css y bugs

---

client/src/App.js
client/src/Components/Cards/cards.css
client/src/Components/Cards/categoryContainer.jsx
client/src/Components/Cards/productsContainer.jsx
client/src/Components/HomeAdmin/HomeAdmin.jsx
client/src/Components/NavBar/NavBar.css
client/src/Components/NavBar/NavBar.jsx
client/src/Views/Home/Home.jsx

Se saco el btn de Home Admin. Para insertarlo en el Navbar. Solo se ve si sos admin
Este redirige al home tal cual como lo ve el User comun
Tambien se le agregaron 2 btn para volver a centro info del admin

Correcciones en Admin

---

client/src/Components/ListUser-Admin/Users.jsx
client/src/Components/Stock/Stock.jsx
client/src/Views/Home/Home.jsx
client/src/redux/actions/productActions.js
client/src/redux/constants/productConstants.js
client/src/redux/reducers/productReducers.js

traten con amor y cariño al filtro de "desactive" ♥

add functions ListOrders

---

client/src/Components/NavBar/NavBar.css
client/src/Components/Stock/Stock.css
client/src/Views/Home/Home.css
client/src/Views/Home/Home.jsx

Se hicieron cambios en el css en el Admin

cambios en el css

---

api/src/routes/userRoutes.js

modificaciòn en la ruta del back para que en el front salga mensaje si el usuario se habìa registrado previamente con google.
Antes salìa el mensaje general de mongo porque el usuario estaba repetido

mensaje de login con google

---

api/src/routes/order.js
client/src/Components/Charts/Charts.css
client/src/Components/Charts/Charts.jsx

falta sacar mail harcodeado y poner mail de usuario

arreglo mail
